memory_path: "task_memory.jsonl"
temp_dir: "temp"
cache_dir: "cache"
max_temp_mb: 500
max_cache_mb: 500
cache_check_interval: 300
plugin_dir: "plugins"
tts_voice: "tts_models/en/vctk/vits"
tts_cache_dir: "tts_cache"
browser_user_agent: null
browser_proxy: null
browser_headless: true

# Feature flags allow subsystems to be toggled without code changes
features:
  browser_automation: true
  tts: true
  plugins: true
