memory_path: "task_memory.jsonl"
temp_dir: "temp"
cache_dir: "cache"
max_temp_mb: 500
max_cache_mb: 500
cache_check_interval: 300
plugin_dir: "plugins"
tts_voice: "tts_models/en/vctk/vits"
tts_cache_dir: "tts_cache"
browser_user_agent: null
browser_proxy: null
browser_headless: true

features:
  plugins:
    enabled: true
  text_to_speech:
    enabled: true
  browser_automation:
    enabled: true
  safety_filters:
    enabled: true  # Disabling removes censorship and safety checks. Use with caution.
